packages:
  # Applications - deployable services
  - 'packages/apps/*'
  
  # Shared libraries - reusable packages
  - 'packages/libs/*'
  
  # Additional packages (e.g., integration tests)
  - 'packages/integration-tests/*'